// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: New_UI_DPV

#ifndef _NEW_UI_DPV_UI_H
#define _NEW_UI_DPV_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_img_final_png);    // assets/img/final.png

// FONTS
LV_FONT_DECLARE(ui_font_DPV128);
LV_FONT_DECLARE(ui_font_DPV220);
LV_FONT_DECLARE(ui_font_DPV256);
LV_FONT_DECLARE(ui_font_DPV80);
LV_FONT_DECLARE(ui_font_DPV80new);
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
