// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: New_UI_DPV

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_DEPTH;
extern lv_obj_t * ui_GEAR;
extern lv_obj_t * ui_SPEED;
extern lv_obj_t * ui_TIME;
extern lv_obj_t * ui_BATTERY;
extern lv_obj_t * ui_DIRECTION;
extern lv_obj_t * ui_TEMP;
extern lv_obj_t * ui_ICONALERT;
extern lv_obj_t * ui_ICONDEPTH;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

