// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: New_UI_DPV

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_deep = NULL;
lv_obj_t * ui_gear = NULL;
lv_obj_t * ui_speed = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_percentage = NULL;
lv_obj_t * ui_direction = NULL;
lv_obj_t * ui_temp = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_img_final_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_deep = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_deep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_deep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_deep, -283);
    lv_obj_set_y(ui_deep, -15);
    lv_obj_set_align(ui_deep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_deep, "0");
    lv_obj_set_style_text_font(ui_deep, &ui_font_DPV128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gear = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_gear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gear, 252);
    lv_obj_set_y(ui_gear, -19);
    lv_obj_set_align(ui_gear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gear, "0");
    lv_obj_set_style_text_font(ui_gear, &ui_font_DPV128, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speed = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_speed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speed, -1);
    lv_obj_set_y(ui_speed, -13);
    lv_obj_set_align(ui_speed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speed, "0");
    lv_obj_set_style_text_color(ui_speed, lv_color_hex(0xB8B8B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speed, &ui_font_DPV220, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, -162);
    lv_obj_set_y(ui_time, 191);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "0");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_DPV80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_percentage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_percentage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_percentage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_percentage, 105);
    lv_obj_set_y(ui_percentage, 190);
    lv_obj_set_align(ui_percentage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_percentage, "0");
    lv_obj_set_style_text_color(ui_percentage, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_percentage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_percentage, &ui_font_DPV80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_direction = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_direction, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_direction, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_direction, -3);
    lv_obj_set_y(ui_direction, -169);
    lv_obj_set_align(ui_direction, LV_ALIGN_CENTER);
    lv_label_set_text(ui_direction, "0");
    lv_obj_set_style_text_color(ui_direction, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_direction, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_direction, &ui_font_DPV80new, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, 1);
    lv_obj_set_y(ui_temp, 131);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp, "0");
    lv_obj_set_style_text_color(ui_temp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_temp, &ui_font_DPV80new, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image2 = NULL;
    ui_deep = NULL;
    ui_gear = NULL;
    ui_speed = NULL;
    ui_time = NULL;
    ui_percentage = NULL;
    ui_direction = NULL;
    ui_temp = NULL;

}
